# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GiozoxgeGJ1wD2P2WUI5SZTYNTG3VYXr
"""

import pandas as pd
malumot={
    "FISH":[ "Nematjoniva Dilshoda","Mamadaliyeva Xurshida","Abduhayotova Shahlo","Adusattorov Rustam","Abdumalikov Abdusalom","Abdumalikov Anvarjon","Azizov Begzod","Abdusattorov Abdujalil","Davronboyeva Sarvinoz","Qahramonov Pahlavon"     ],
    "Yoshi":[ "20","19","21","20","19","19","15","16","15","14", ],
    "jinsi":[  "Qiz","Qiz","Qiz","Erkak","Erkak","Erkak","Erkak","Erkak","Erkak","Erkak", ],
    "Qaysi maktabda uqishi":[  "1","2","3","4","5","6","7","8","9","10"  ],
    "Manzili":[  "toshkent","samarqand","Fargona ","andijon","Namangan","buxoro","fargona","surxondaryo","toshkent","buxoro"   ]

}
db=pd.DataFrame(malumot)
print(db)

Filtr=db[(db['jinsi']=="Erkak") & (db["Yoshi"]>'15')]
print(Filtr)